version: '3,3'

services:
  db: 
    container_name: 'db'
    image: postgres:latest
    ports:
      - '5433:5433'
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - local-net
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '80:80'
    depends_on:
      - db
    env_file:
      - .env
  
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - pgadmin
    env_file:
      - .env
    restart: on-failure
    networks:
      - local-net
    ports:
      - "8000:8001"

networks:
  local-net:
    driver: bridge